Floating button finished
Arquisoft/viade_en2b pull request #68
Opened 2020-03-13 18:22 UTC by UO264255

Actions are not really needed for this delivery. Also maybe we should improve its visuals(icons) but, again, not really important right now

2020-03-13 20:23 UTC, miguilucky approved these changes

2020-03-14 08:41 UTC, ClaraMirandaGarcia approved these changes

2020-03-14 13:23 UTC, guillefun approved these changes

2020-03-14 15:34 UTC, violetaruizm approved these changes

2020-03-14 16:53 UTC, UO264345 requested changes
The package.json conflicts need to be addressed before merging.

2020-03-14 17:25 UTC, UO264345 approved these changes

2020-03-14 17:32 UTC, merged